spring:
    application:
        name: stock-pulse
    datasource:
        url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}?sslmode=require
        username: ${PGUSER}
        password: ${PGPASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            connection-timeout: 20000
            idle-timeout: 300000
            max-lifetime: 1200000

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                use_sql_comments: true
                jdbc:
                    batch_size: 20
                    order_inserts: true
                    order_updates: true

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration
        validate-on-migrate: true